Fix package detection on centos in bootstrap
Signed-off-by: Josh Durgin <josh.durgin@inktank.com>

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,16 +1,30 @@
 #!/bin/sh
 set -e
 
-for package in python-pip python-virtualenv python-dev libevent-dev; do
-    if [ "$(dpkg --status -- $package|sed -n 's/^Status: //p')" != "install ok installed" ]; then
-	# add a space after old values
-	missing="${missing:+$missing }$package"
+if [ -f /etc/debian_version ]; then
+    for package in python-pip python-virtualenv python-dev libevent-dev; do
+        if [ "$(dpkg --status -- $package 2>/dev/null|sed -n 's/^Status: //p')" != "install ok installed" ]; then
+            # add a space after old values
+            missing="${missing:+$missing }$package"
+        fi
+    done
+    if [ -n "$missing" ]; then
+        echo "$0: missing required packages, please install them:" 1>&2
+        echo "  sudo apt-get install $missing"
+        exit 1
     fi
-done
-if [ -n "$missing" ]; then
-    echo "$0: missing required packages, please install them:" 1>&2
-    echo "sudo apt-get install $missing"
-    exit 1
+fi
+if [ -f /etc/redhat-release ]; then
+    for package in python-pip python-virtualenv python-devel libevent-devel; do
+        if [ "$(rpm -qa $package 2>/dev/null)" == "" ]; then
+            missing="${missing:+$missing }$package"
+        fi
+    done
+    if [ -n "$missing" ]; then
+        echo "$0: missing required packages, please install them:" 1>&2
+        echo "  sudo yum install $missing"
+        exit 1
+    fi
 fi
 
 virtualenv --no-site-packages --distribute virtualenv
